//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGoogleCalendarServices.Web.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsAttendee
    {
        public int Id { get; set; }
        public string EventAppId { get; set; }
        public string GoogleId { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
